//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentagon.ConsolePresentation.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pentagon.Utilities.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;codes&quot;: [
        ///	{
        ///	  &quot;code&quot;: 0,
        ///	  &quot;symbol&quot;: &quot;NULL&quot;,
        ///	  &quot;type&quot;: &quot;control&quot;,
        ///	  &quot;description&quot;: &quot;Null character&quot;
        ///	},
        ///	{
        ///	  &quot;code&quot;: 1,
        ///	  &quot;symbol&quot;: &quot;SOH&quot;,
        ///	  &quot;type&quot;: &quot;control&quot;,
        ///	  &quot;description&quot;: &quot;Start of Header&quot;
        ///	},
        ///	{
        ///	  &quot;code&quot;: 2,
        ///	  &quot;symbol&quot;: &quot;STX&quot;,
        ///	  &quot;type&quot;: &quot;control&quot;,
        ///	  &quot;description&quot;: &quot;Start of Text&quot;
        ///	},
        ///	{
        ///	  &quot;code&quot;: 3,
        ///	  &quot;symbol&quot;: &quot;ETX&quot;,
        ///	  &quot;type&quot;: &quot;control&quot;,
        ///	  &quot;description&quot;: &quot;End of Text&quot;
        ///	},
        ///	{
        ///	  &quot;code&quot;: 4,
        ///	  &quot;symbol&quot;: &quot;EOT&quot;,
        ///	  &quot;type&quot;: &quot;control&quot;,
        ///	  &quot;description&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ASCIITable {
            get {
                return ResourceManager.GetString("ASCIITable", resourceCulture);
            }
        }
    }
}
